#!/usr/bin/env ruby
require 'rake/testtask'
Rake::TestTask.new do |t|
  t.libs << File.join(File.dirname(File.dirname __FILE__), "bin")
  t.test_files = Dir.glob "#{File.dirname __FILE__}/**/*_test.rb"
  t.warning = true
end
